apiVersion: v1
kind: Service
metadata:
  name: kv-store-service
spec:
  type: NodePort
  selector:
    app: kv-store
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000