apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kv-store
  template:
    metadata:
      labels:
        app: kv-store
    spec:
      containers:
        - name: kv-store
          image: docker.io/mostojic/key-value-store:latest
          ports:
            - containerPort: 5000